import Head from "next/head";
import Link from "next/link";
import { api } from "@/utils/api";
import { useUser } from "@auth0/nextjs-auth0/client";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { user, error, isLoading } = useUser();

  if (isLoading) return <div>Loading...</div>;
  console.log("user", user);

  // console.log("erorr", error);

  // if (error) return <div>{error.message}</div>;

  // console.log("user", user);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello</h1>
        {user ? (
          <div>
            {user.name} ({user.email})
            <div>
              <Link href={"/api/auth/logout"}>Logout</Link>
            </div>
          </div>
        ) : (
          <div>
            Not logged in <Link href={"/api/auth/login"}>Login</Link>
          </div>
        )}
      </main>
    </>
  );
}
