import React from "react";
import Head from "next/head";
import Link from "next/link";
import { api } from "@/utils/api";
import { useUser } from "@auth0/nextjs-auth0/client";

type Settings = {
  title: string;
};

type Homepage = {
  title: string;
};

export type HomeViewProps = {
  page: Homepage;
  settings: Settings;
};

export const HomeView = ({ page, settings }: HomeViewProps) => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { user, error, isLoading } = useUser();

  if (isLoading) return <div>Loading...</div>;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="my-10 bg-orange-200 p-4 text-3xl">{page.title}</h1>

        <main className="mx-auto max-w-7xl px-10">
          {user ? (
            <div>
              {user.name} ({user.email})
              <div>
                <Link href={"/api/auth/logout"}>Logout</Link>
              </div>
            </div>
          ) : (
            <div>
              Not logged in <Link href={"/api/auth/login"}>Login</Link>
            </div>
          )}
        </main>
      </div>
    </>
  );
};

export default HomeView;
