import React from "react";
import Head from "next/head";
import Link from "next/link";
import { api } from "@/utils/api";
import { useUser } from "@auth0/nextjs-auth0/client";

type Settings = {
  title: string;
};

type Homepage = {
  title: string;
};

export type HomeViewProps = {
  page: Homepage;
  settings: Settings;
};

export const HomeView = ({ page, settings }: HomeViewProps) => {
  const { data, isLoading: isDataLoading } = api.example.hello.useQuery({
    text: "from tRPC",
  });

  const { data: products, isLoading: isExampleLoading } =
    api.products.getUserProducts.useQuery();

  console.log("products", products);

  const { data: exampleData, isLoading: isExampleDataLoading } =
    api.example.test.useQuery();

  // console.log("postsData", postsData);
  // console.log("exampleData", exampleData);

  const { mutate } = api.example.addExample.useMutation();
  const productMutation = api.products.create.useMutation();

  const savePostMutation = api.users.savePost.useMutation();

  const { user, error, isLoading: isUserLoading } = useUser();

  if (isUserLoading || isDataLoading) return <div>Loading...</div>;

  const addProduct = () => {
    try {
      const res = productMutation.mutateAsync({
        title: "My first product title",
      });
      console.log("res", res);
    } catch (error) {
      console.log("error", error);
    }
  };

  const handleSavePost = () => {
    try {
      const response = savePostMutation.mutate({
        userId: "clkh8omjc0000sox653k7alh2",
        productId: "clkh8vpl10000so7o6v01wngo",
      });
      console.log("response", response);
    } catch (error) {
      console.log("error", error);
    }
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="my-10 bg-orange-200 p-4 text-3xl">{page.title}</h1>
        <div>{data.greeting}</div>
        <div className="flex flex-col gap-2 p-4">
          <button onClick={addProduct}>Add new product</button>
          <button onClick={handleSavePost}>Update user with saved post</button>
        </div>

        <main className="mx-auto max-w-7xl px-10">
          {user ? (
            <div>
              {user.name} ({user.email})
              <div>
                <Link href={"/api/auth/logout"}>Logout</Link>
              </div>
            </div>
          ) : (
            <div>
              Not logged in <Link href={"/api/auth/login"}>Login</Link>
            </div>
          )}
        </main>
      </div>
    </>
  );
};

export default HomeView;
